# Site settings
title: Simon Knibbs
email: simon.knibbs@gmail.com
description: "I am a software engineer with 5 years industry experience. The languages I work with most are Python & HTML/CSS/JS and C/C++ for low-level work."
baseurl: ""
url: "https://s-knibbs.github.io"
github_username: s-knibbs
linkedin_userid: simon-knibbs-41a7462b
# CDN url to serve images.
cdn: https://dl.dropboxusercontent.com/u/2874365/site-images/

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Default variables for the YAML Front Matter
defaults:
  -  # set the 'is_post' variable to true for posts
    scope:
      path: ""
      type: posts
    values:
      is_post: true
