# Site settings
title: Simon Knibbs
email: simon.knibbs@gmail.com
description: "I am a software engineer with 5 years industry experience. The languages I work with most are Python & HTML/CSS/JS and C/C++ for low-level work."
baseurl: ""
url: "https://s-knibbs.github.io"
github_username:  s-knibbs
linkedin_userid:  simon-knibbs-41a7462b

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - algoliasearch-jekyll
