# Production config
environment: production

# Site settings
title: Simon Knibbs
author: Simon J Knibbs
email: simon.knibbs@gmail.com
description: "Software engineer with 5 years industry experience. The languages I work with most are Python & HTML/CSS/JS and C/C++ for low-level work."
baseurl: ""
reponame: s-knibbs.github.io
url: "https://s-knibbs.github.io"

# Social media
twitter_username: sjknibbs
github_username: s-knibbs
linkedin_userid: simon-knibbs-41a7462b

# External URLs
social:
  links:
    - "https://uk.linkedin.com/in/simon-knibbs-41a7462b"

font_styles:
  - "https://fonts.googleapis.com/css?family=Roboto:300,400,700"
  - "https://fonts.googleapis.com/css?family=Oxygen:400,700"
  - "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"

# CDN url to serve images.
cdn: https://dl.dropboxusercontent.com/u/2874365/site-images/
jquery_url: https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
safe: false
exclude:
  - "package.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.sh"
  - "index-build.log"

sass:
  style: compressed

# Gems
gems:
  - jekyll-seo-tag
  - build-extras
  - jekyll-github-metadata

# Default variables for the YAML Front Matter
defaults:
  -  # set the 'is_post' variable to true for posts
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      stylesheets:
        - "/css/post.css"
        - "/css/highlight.css"
      scripts:
        - "/js/embed-svg-loader.js"
  -
    scope:
      path: ""
      type: pages
    values:
      stylesheets:
        - "/css/post.css"
  -
    scope:
      path: "photos"
    values:
      stylesheets:
        - "/css/gallery.css"

global_scripts:
    - "/js/highlight-search.js"
    - "/js/shortcuts.js"
    - "/js/header-link.js"
    - "/js/sw-registration.js"
