# Development config - overrides for the production config.
environment: development
future: true

exclude:
  - "package.json"
  - "*.min.js"  # Exclude minified javascript
  - "*.min.css" # Exclude minified CSS
  - "*.sh"
  - "Gemfile"
  - "Gemfile.lock"
  - "index-build.log"
  - "data/tag-index.json" # Exclude all build generate data to prevent infinite rebuild loop.
  - "data/cache-config.min.js"
  - "data/index.json"
  - "data/language-totals.json"

# Always include third-party minified libraries
include:
  - "elasticlunr.min.js"
  - "mustache.min.js"
  - "index.min.js"
  - "bowser.min.js"

# Disable HTML minification
compress_html:
  blanklines: true

dev_scripts:
    - "/js/auto-reload.js"
    - "/js/enable-editing.js"
